dbt_test_project:
  outputs:
    prod:
      dataset: google_sheets
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: gcp-training-329609-bd9dbabb0fa8.json
      location: US
      method: service-account
      priority: interactive
      project: gcp-training-329609
      threads: 1
      type: bigquery
  target: prod
